name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          
      - name: Allow gradlew permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug
          
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload output metadata
        uses: actions/upload-artifact@v3
        with:
          name: output-metadata
          path: app/build/outputs/apk/debug/output-metadata.json